import { describe, it, expect } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(import.meta.dir, "..", "..", "..");
const FIXTURE_PATH = join(REPO_ROOT, "out", "modern-day.json");

// Match the UUID-v4-style suffix that Pax geometry feature keys leak into
// regionOwnershipOverrides when the transform's remap path is absent or the
// fixture was generated by an older transform that emitted Pax keys verbatim.
const UUID_SUFFIX_PATTERN = /[0-9a-f]{8}-[0-9a-f]{4}-/;

describe("regression: out/modern-day.json fixture invariants", () => {
  it("has zero UUID-suffix override keys in data.world.regionOwnershipOverrides", () => {
    const bundle = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Record<string, unknown>;
    const data = bundle.data as Record<string, unknown>;
    const world = data.world as Record<string, unknown>;
    const overrides = world.regionOwnershipOverrides as Record<string, unknown>;

    const uuidKeys = Object.keys(overrides).filter((k) => UUID_SUFFIX_PATTERN.test(k));
    expect(uuidKeys).toEqual([]);
  });

  it("backgroundData presence matches the modern-day fixture's basemap geometry availability", () => {
    // The modern-day fixture is the committed canonical (rebuilt by export-smoke
    // from the cold-war fixture). backgroundData appears iff the fixture's
    // editor capture supplied basemap geometry. The cold-war fixture (per Task 3
    // of the basemap-capture plan) has a fabricated editor_state_raw.json with
    // 2 stub regions, so backgroundData is expected after this plan lands.
    const bundle = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Record<string, unknown>;
    const assets = bundle.assets as Record<string, unknown>;
    const hasBackgroundData = "backgroundData" in assets;
    // After basemap-capture plan lands with the cold-war fixture fabricated,
    // backgroundData MUST be present. If a future commit drops the fixture
    // edit, this test will catch the regression.
    expect(hasBackgroundData).toBe(true);
  });
});